---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
# https://github.com/willthames/ansible-lint/issues/315
# Avoid this issue with 'with_filetree'
# use -x flag with ANSIBLE0015
lint: |
  set -e
  yamllint -c molecule/default/yaml-lint.yml .
  ansible-lint -x ANSIBLE0015
  flake8
platforms:
  - name: instance
    image: joshuacherry/docker-${MOLECULE_DISTRO:-ubuntu1604}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-"/lib/systemd/systemd"}
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
