---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: joshuacherry/docker-${MOLECULE_DISTRO:-ubuntu1604}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-"/lib/systemd/systemd"}
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        # https://github.com/willthames/ansible-lint/issues/315
        # Avoid this issue with 'with_filetree'
        - ANSIBLE0015
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: proxy
verifier:
  name: testinfra
  lint:
    name: flake8
